name: applescript
version: 0.0.8
author: Christopher Su <chris+dart@christopher.su>
description: A library for executing AppleScript in Dart.
homepage: https://github.com/csu/applescript.dart
documentation: https://github.com/csu/applescript.dart
